blogarts/article/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.article_home),
    ]

blogarts/blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.blog_home, {'url_name':'blogs', 
                                 'get':views.get_blog_home,
                                 'post':views.post_blog_home}),
    url(r'^added/$', views.blog_added),
    ]

blogarts/blogarts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blogs/', include('blog.urls')),
    url(r'^articles/', include('article.urls')),
    url(r'^$', 'blogarts.views.home'),
    url(r'^register/$', 'blog.views.register'),
    url(r'^register/thanks$', 'blog.views.register_thanks'),
]

blogarts/article/models.py
from django.db import models

# Create your models here.

blogarts/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    
    name = models.CharField(verbose_name='namE', max_length=100)
    email = models.EmailField(verbose_name='E-maIl')
    
    def __str__(self):
        return self.name
    
class Blog(models.Model):
    
    title = models.CharField(verbose_name = 'TitLe', max_length=100)
    author = models.ForeignKey(Author,verbose_name = 'WriTTen bY')
    content = models.TextField(verbose_name = 'cONtEnt')
    published = models.DateTimeField(verbose_name='WRItten ON')

    def __str__(self):
        return self.title
    
class UserProfile(models.Model):
    
    user = models.OneToOneField(User)
    
    profile_picture = models.ImageField(upload_to='profile_images', blank=True)
    
    def __str__(self):
        return self.user.username

blogarts/blog/forms.py
from django import forms
from django.contrib.auth.models import User

from . import models

class SearchForm(forms.Form):
    
    name = forms.CharField(max_length=100, label='')
    
class AddBlogForm(forms.Form):
    
    title = forms.CharField(max_length=100)
    message = forms.CharField(label = '', widget=forms.Textarea)
    email = forms.EmailField()

#    class Meta:
#        model = models.Blog
#        fields = ('title', 'author', 'content', 'published')

class UserForm(forms.ModelForm):
    
    password = forms.CharField(max_length=100, widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        
class UserProfileForm(forms.ModelForm):
    
    class Meta:
        model = models.UserProfile
        fields = ('profile_picture',)

blogarts/article/views.py
from django.shortcuts import render

def article_home(request):
    return render(request, 'article/article_home_template.html', {})

blogarts/blog/views.py
import datetime

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse

from . import forms, models
from .forms import UserForm, UserProfileForm

def blog_home(request, url_name, get, post):
    
    if request.method == 'GET':
        return get(request, url_name)

    if request.method == 'POST':
        return post(request)
    raise Http404
  

def get_blog_home(request, url_name):

#    print request.META
    print "hi"
    print "hello"
    http_referer = request.META['HTTP_REFERER']

    if url_name in http_referer and request.GET == {}:
        form = forms.AddBlogForm(initial={'message':'Write here'})
        return render(request, 'blog/blog_add_template.html', {'form':form})

    elif 'name' in request.GET:
        form = forms.AddBlogForm()
        blog = models.Blog.objects.filter(title=request.GET['name'])        
        return render(request, 'blog/blog_search_template.html', {'query':request.GET['name'],'blog':blog, 'form':form})

    form = forms.SearchForm(initial={'name':'Blog'})
    return render(request, 'blog/blog_home_template.html', {'form':form})

def post_blog_home(request):

    form = forms.AddBlogForm(request.POST)

    if form.is_valid():

        cd = form.cleaned_data
        title = cd['title']
        message = cd['message']

        b = models.Blog(title=title, author=models.Author.objects.get(name='Sahil'), content=message, published=datetime.datetime.now())
        b.save()

        return HttpResponseRedirect('/blogs/added')

    return render(request, 'blog/blog_add_template.html', {'form':form})


def blog_added(request):
    
    return render(request, 'blog/blog_added_template.html', {})
    
def register(request):
    
    registered = False
    if request.method == 'POST':
        
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            
            user.set_password(user.password)
            user.save()
            
            profile = profile_form.save(commit=False)
            profile.user = user
            
            if 'profile_picture' in request.FILES:
                
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
            
            return HttpResponseRedirect('thanks')
        else:
            print user_form.errors, profile_form.errors
            
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
        
    return render(request, 
           'login/register.html', 
           {'user_form':user_form, 
            'profile_form': profile_form,
            'registered':registered}
           )

def register_thanks(request):
    
    return HttpResponse('Thank you for registering\n')

blogarts/blogarts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

def home(request):
    return render(request, 'home/home_template.html', {})

blogarts/templates/article/article_home_template.html
<html>
    <title>ArticleS|BlogArtS</title>
    <h>Welcome to ArticlE Section</h>
</html>

blogarts/templates/base_blog.html
<div class="field">
    {{ form.title.errors }}
    <label for="id_title">Title:</label>
    {{ form.title }}
</div>

<div class="field">
    {{ form.email.errors }}
    <label for="id_email">Your e-mail address:</label>
    {{ form.email }}
</div>

<div class="field">
    {{ form.message.errors }}
    <label for="id_message"></label>
    {{ form.message }}
</div>

blogarts/templates/blog/blog_add_template.html
<html>
<head>
    <title>Add|Blogs</title>
</head>
{% include "head.html" %}
<body>
    <h1>Write here</h1>

    {% if form.errors %}
        <p style="color:red;">
            Please correct the error{{form.errors|pluralize}} below
        </p>
    {% endif %}

    <form action='' method='post'>
        {% csrf_token %}
        {% include "base_blog.html" with form=form %}

<!--
        <div class="field">
            {{ form.title.errors }}
            <label for="id_title">Title:</label>
            {{ form.title }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message"></label>
            {{ form.message }}
        </div>
-->

        <input type='submit' value='Save'></input>
    </form>
</body>
</html>

blogarts/templates/blog/blog_added_template.html
<p>Your blog has been saved.</p>
<p>Thank YoU.</p>

blogarts/templates/blog/blog_home_template.html
<html>
    <title>BloGS|BlogArtS</title>
    <h>Welcome to BlOg Section</h>
    <br></br>
    <br></br>
    <body>
        <form action=''>
            {{ form.as_table }}
            <input type='submit' value='Search'></input>
        </form>
        <form action=''>
            <p>Write a Blog <input type='submit' value='Try your hand'></input></p>
        </form>
    </body>
</html>

blogarts/templates/blog/blog_search_template.html
<p>You searched for: <strong>{{ query }}</strong></p>
{% if blog %}
<p>Found {{ blog|length }} blog{{ blog|pluralize }}.</p>
<ul>
    {{ request.REMOTE_ADDR }}
    {% for b in blog %}
    <li>
        {{b.content}}
    </li>
    {% endfor %}
</ul>
{% else %}
    <p>No blogs matched your search criteria.</p>
{% endif %}

blogarts/templates/head.html
<h style='color:red;'>ThE BlogArtS</h>

blogarts/templates/home/home_template.html
<html>
    <title>BlogArtS</title>
    <h style='color:red;'>ThE BlogArtS</h>
    <body>
        <p>Welcome bloggers and articlers</p>
        <form action='/articles/'>
            <input type='submit' value='ArticleS'></input>
        </form>
        <form action='/blogs/'>
            <input type='submit' value='BlogS'></input>
        </form>
        <a href="http://www.w3schools.com">Visit W3Schools.com!</a> 
    </body>
</html>

blogarts/templates/login/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>BlogArtS</title>
    </head>

    <body>
        <h1>Register with BlogArtS</h1>

        {% if registered %}
        BlogArts says: <strong>thank you for registering!</strong>
        <a href="/">Return to the homepage.</a><br />
        {% else %}
        BlogArts says: <strong>register here!</strong><br />

        <form id="user_form" method="post" action=""
                enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
    </body>
</html>